import type {
  Attachment,
  ActivityLog,
  ChangeOrder,
  Customer,
  Inquiry,
  InvoiceDraft,
  MaterialEntry,
  AppNotification,
  Organization,
  Project,
  Quote,
  TimeEntry,
  User,
  WorkOrder,
} from "@/lib/types";

/* Date helpers — everything is anchored to "today" so the demo feels live. */
const DAY = 86400000;
function atTime(base: Date, h: number, m = 0) {
  const d = new Date(base);
  d.setHours(h, m, 0, 0);
  return d.toISOString();
}
function dayISO(offsetDays: number) {
  const d = new Date();
  d.setHours(12, 0, 0, 0);
  return new Date(d.getTime() + offsetDays * DAY).toISOString();
}
function dateOnly(offsetDays: number) {
  return dayISO(offsetDays).slice(0, 10);
}

export interface SeedData {
  organization: Organization;
  users: User[];
  customers: Customer[];
  inquiries: Inquiry[];
  quotes: Quote[];
  projects: Project[];
  workOrders: WorkOrder[];
  timeEntries: TimeEntry[];
  materials: MaterialEntry[];
  attachments: Attachment[];
  changeOrders: ChangeOrder[];
  invoiceDrafts: InvoiceDraft[];
  notifications: AppNotification[];
  activity: ActivityLog[];
}

const ORG_ID = "org_nordic";

export function buildSeed(): SeedData {
  const today = new Date();

  const organization: Organization = {
    id: ORG_ID,
    name: "Nordic Måleri AB",
    orgNumber: "556712-3489",
    industry: "Måleri",
    email: "info@nordicmaleri.se",
    phone: "08-123 45 67",
    address: "Verkstadsgatan 12, 117 43 Stockholm",
    logoText: "NM",
    defaultVatRate: 25,
    currency: "SEK",
    paymentTerms: "30 dagar netto",
    quoteTerms:
      "Offerten är giltig i 30 dagar. Priser anges exklusive moms om inget annat anges. ROT-avdrag tillämpas enligt gällande regler. Arbetet utförs enligt branschstandard AB04.",
    quoteNumberPrefix: "OFF-2026-",
    workOrderNumberPrefix: "AO-2026-",
  };

  const users: User[] = [
    {
      id: "u_anna",
      organizationId: ORG_ID,
      name: "Anna Lind",
      email: "anna@nordicmaleri.se",
      role: "admin",
      title: "VD / Administratör",
      phone: "070-111 22 33",
      active: true,
      hourlyRate: 650,
      color: "#6d5efc",
    },
    {
      id: "u_johan",
      organizationId: ORG_ID,
      name: "Johan Ek",
      email: "johan@nordicmaleri.se",
      role: "supervisor",
      title: "Arbetsledare",
      phone: "070-222 33 44",
      active: true,
      hourlyRate: 595,
      color: "#0ea5e9",
    },
    {
      id: "u_erik",
      organizationId: ORG_ID,
      name: "Erik Nilsson",
      email: "erik@nordicmaleri.se",
      role: "worker",
      title: "Målare",
      phone: "070-333 44 55",
      active: true,
      hourlyRate: 545,
      color: "#16a34a",
    },
    {
      id: "u_sara",
      organizationId: ORG_ID,
      name: "Sara Ali",
      email: "sara@nordicmaleri.se",
      role: "worker",
      title: "Målare",
      phone: "070-444 55 66",
      active: true,
      hourlyRate: 545,
      color: "#f59e0b",
    },
  ];

  const customers: Customer[] = [
    {
      id: "c_anders",
      organizationId: ORG_ID,
      type: "private",
      name: "Anders Andersson",
      phone: "070-555 11 22",
      email: "anders.andersson@gmail.com",
      addresses: [
        {
          id: "addr_a1",
          label: "Hemadress",
          type: "work",
          street: "Storgatan 5, lgh 1203",
          postalCode: "114 51",
          city: "Stockholm",
        },
        {
          id: "addr_a2",
          label: "Fakturaadress",
          type: "invoice",
          street: "Storgatan 5, lgh 1203",
          postalCode: "114 51",
          city: "Stockholm",
        },
      ],
      notes: "Önskar SMS innan besök. Katt i hemmet.",
      createdAt: dayISO(-120),
    },
    {
      id: "c_brf",
      organizationId: ORG_ID,
      type: "company",
      name: "BRF Solgläntan",
      companyName: "Bostadsrättsföreningen Solgläntan",
      orgNumber: "769612-1145",
      phone: "08-556 77 88",
      email: "styrelse@solglantan.se",
      addresses: [
        {
          id: "addr_b1",
          label: "Fastighet",
          type: "work",
          street: "Solvägen 22",
          postalCode: "129 32",
          city: "Hägersten",
        },
        {
          id: "addr_b2",
          label: "Fakturaadress",
          type: "invoice",
          street: "Box 442",
          postalCode: "129 04",
          city: "Hägersten",
        },
      ],
      notes: "Kontaktperson: ordförande Margareta Holm.",
      createdAt: dayISO(-95),
    },
    {
      id: "c_fastpartner",
      organizationId: ORG_ID,
      type: "company",
      name: "Fastighetspartner Sverige AB",
      companyName: "Fastighetspartner Sverige AB",
      orgNumber: "556998-2210",
      phone: "08-700 10 20",
      email: "drift@fastighetspartner.se",
      addresses: [
        {
          id: "addr_f1",
          label: "Huvudkontor",
          type: "invoice",
          street: "Kungsgatan 44",
          postalCode: "111 35",
          city: "Stockholm",
        },
        {
          id: "addr_f2",
          label: "Objekt: Kvarteret Eken",
          type: "work",
          street: "Ekvägen 8",
          postalCode: "168 53",
          city: "Bromma",
        },
      ],
      notes: "Ramavtalskund. Fakturareferens krävs på varje order.",
      createdAt: dayISO(-80),
    },
  ];

  const inquiries: Inquiry[] = [
    {
      id: "i_1",
      organizationId: ORG_ID,
      customerName: "Karin Bergström",
      phone: "070-981 22 10",
      email: "karin.bergstrom@telia.com",
      address: "Lindvägen 3, 167 62 Bromma",
      workType: "Inomhusmålning",
      description: "Vill måla om vardagsrum och hall, ca 45 m².",
      desiredDate: dateOnly(21),
      source: "Webbformulär",
      ownerId: "u_anna",
      status: "new",
      createdAt: dayISO(-1),
    },
    {
      id: "i_2",
      organizationId: ORG_ID,
      customerName: "Peter Sjögren",
      companyName: "Café Smultron",
      phone: "070-444 88 12",
      email: "peter@cafesmultron.se",
      address: "Hornsgatan 90, 118 21 Stockholm",
      workType: "Fasad & skylt",
      description: "Behöver måla om fasad och fräscha upp entré inför säsong.",
      desiredDate: dateOnly(35),
      source: "Telefon",
      ownerId: "u_johan",
      status: "contacted",
      createdAt: dayISO(-3),
    },
    {
      id: "i_3",
      organizationId: ORG_ID,
      customerName: "Margareta Holm",
      companyName: "BRF Solgläntan",
      phone: "08-556 77 88",
      email: "styrelse@solglantan.se",
      address: "Solvägen 22, 129 32 Hägersten",
      workType: "Trapphus",
      description: "Renovering av två trapphus, slitna väggar och tak.",
      desiredDate: dateOnly(14),
      source: "Rekommendation",
      ownerId: "u_anna",
      status: "visit_booked",
      createdAt: dayISO(-6),
    },
    {
      id: "i_4",
      organizationId: ORG_ID,
      customerName: "Anders Andersson",
      phone: "070-555 11 22",
      email: "anders.andersson@gmail.com",
      address: "Storgatan 5, 114 51 Stockholm",
      workType: "Vattenskada",
      description: "Vattenskada i badrum efter läckage, behöver åtgärdas snabbt.",
      desiredDate: dateOnly(5),
      source: "Återkommande kund",
      ownerId: "u_johan",
      status: "quoting",
      createdAt: dayISO(-4),
    },
  ];

  /* --------------------------------- Quotes -------------------------------- */
  const quotes: Quote[] = [
    {
      id: "q_lgh",
      organizationId: ORG_ID,
      number: "OFF-2026-014",
      customerId: "c_anders",
      title: "Målning av lägenhet",
      description:
        "Komplett ommålning av vardagsrum, hall och sovrum. Inklusive spackling, grundning och två strykningar.",
      status: "approved",
      pricingType: "fixed",
      items: [
        {
          id: "qi_1",
          kind: "labor",
          description: "Förarbete: spackling och slipning",
          quantity: 14,
          unit: "tim",
          unitPrice: 545,
          discountPct: 0,
          vatRate: 25,
        },
        {
          id: "qi_2",
          kind: "labor",
          description: "Målning väggar och tak, 2 strykningar",
          quantity: 28,
          unit: "tim",
          unitPrice: 545,
          discountPct: 0,
          vatRate: 25,
        },
        {
          id: "qi_3",
          kind: "material",
          description: "Färg, spackel och förbrukningsmaterial",
          quantity: 1,
          unit: "st",
          unitPrice: 6400,
          discountPct: 0,
          vatRate: 25,
        },
      ],
      validUntil: dateOnly(8),
      startDate: dateOnly(-2),
      endDate: dateOnly(6),
      terms: organization.quoteTerms,
      paymentTerms: organization.paymentTerms,
      publicToken: "tok_lgh_8f3a2c",
      ownerId: "u_anna",
      createdAt: dayISO(-18),
      sentAt: dayISO(-17),
      openedAt: dayISO(-16),
      approvals: [
        {
          id: "qa_1",
          quoteId: "q_lgh",
          decision: "approved",
          name: "Anders Andersson",
          email: "anders.andersson@gmail.com",
          comment: "Tack, ser bra ut. Kör på!",
          termsAccepted: true,
          ipAddress: "85.226.14.2",
          decidedAt: dayISO(-15),
        },
      ],
      projectId: "p_lgh",
    },
    {
      id: "q_trapphus",
      organizationId: ORG_ID,
      number: "OFF-2026-019",
      customerId: "c_brf",
      title: "Renovering av trapphus",
      description:
        "Renovering av två trapphus inkl. lagning av puts, målning av väggar, tak och snickerier samt rostskydd av räcken.",
      status: "sent",
      pricingType: "estimate",
      items: [
        {
          id: "qi_4",
          kind: "labor",
          description: "Putslagning och förarbete",
          quantity: 40,
          unit: "tim",
          unitPrice: 595,
          discountPct: 0,
          vatRate: 25,
        },
        {
          id: "qi_5",
          kind: "labor",
          description: "Målning väggar, tak och snickerier",
          quantity: 96,
          unit: "tim",
          unitPrice: 595,
          discountPct: 5,
          vatRate: 25,
        },
        {
          id: "qi_6",
          kind: "material",
          description: "Färg och material",
          quantity: 1,
          unit: "st",
          unitPrice: 18500,
          discountPct: 0,
          vatRate: 25,
        },
        {
          id: "qi_7",
          kind: "other",
          description: "Etablering och byggstädning",
          quantity: 1,
          unit: "st",
          unitPrice: 7500,
          discountPct: 0,
          vatRate: 25,
        },
      ],
      validUntil: dateOnly(22),
      startDate: dateOnly(20),
      endDate: dateOnly(48),
      terms: organization.quoteTerms,
      paymentTerms: organization.paymentTerms,
      publicToken: "tok_trapphus_2b9d1e",
      ownerId: "u_anna",
      createdAt: dayISO(-5),
      sentAt: dayISO(-4),
      approvals: [],
    },
    {
      id: "q_fasad",
      organizationId: ORG_ID,
      number: "OFF-2026-021",
      customerId: "c_fastpartner",
      title: "Fasadmålning – Kvarteret Eken",
      description:
        "Tvätt, skrapning och målning av träfasad på flerbostadshus, ca 620 m².",
      status: "opened",
      pricingType: "fixed",
      items: [
        {
          id: "qi_8",
          kind: "labor",
          description: "Ställning, tvätt och skrapning",
          quantity: 60,
          unit: "tim",
          unitPrice: 595,
          discountPct: 0,
          vatRate: 25,
        },
        {
          id: "qi_9",
          kind: "labor",
          description: "Grundning och täckmålning",
          quantity: 120,
          unit: "tim",
          unitPrice: 595,
          discountPct: 0,
          vatRate: 25,
        },
        {
          id: "qi_10",
          kind: "material",
          description: "Fasadfärg och material",
          quantity: 1,
          unit: "st",
          unitPrice: 42000,
          discountPct: 0,
          vatRate: 25,
        },
      ],
      validUntil: dateOnly(25),
      startDate: dateOnly(30),
      endDate: dateOnly(75),
      terms: organization.quoteTerms,
      paymentTerms: organization.paymentTerms,
      publicToken: "tok_fasad_5c7f0a",
      ownerId: "u_johan",
      createdAt: dayISO(-9),
      sentAt: dayISO(-8),
      openedAt: dayISO(-2),
      approvals: [],
    },
    {
      id: "q_vatten",
      organizationId: ORG_ID,
      number: "OFF-2026-022",
      customerId: "c_anders",
      title: "Reparation av vattenskada",
      description:
        "Uttorkning, rivning av skadat ytskikt samt återställning och målning i badrum.",
      status: "draft",
      pricingType: "estimate",
      items: [
        {
          id: "qi_11",
          kind: "labor",
          description: "Rivning och uttorkning",
          quantity: 12,
          unit: "tim",
          unitPrice: 545,
          discountPct: 0,
          vatRate: 25,
        },
        {
          id: "qi_12",
          kind: "labor",
          description: "Återställning och målning",
          quantity: 20,
          unit: "tim",
          unitPrice: 545,
          discountPct: 0,
          vatRate: 25,
        },
        {
          id: "qi_13",
          kind: "material",
          description: "Material och tätskikt",
          quantity: 1,
          unit: "st",
          unitPrice: 8900,
          discountPct: 0,
          vatRate: 25,
        },
      ],
      validUntil: dateOnly(30),
      terms: organization.quoteTerms,
      paymentTerms: organization.paymentTerms,
      publicToken: "tok_vatten_9a1b3d",
      ownerId: "u_johan",
      createdAt: dayISO(-1),
      approvals: [],
    },
  ];

  /* -------------------------------- Projects ------------------------------- */
  const projects: Project[] = [
    {
      id: "p_lgh",
      organizationId: ORG_ID,
      name: "Målning av lägenhet – Andersson",
      customerId: "c_anders",
      quoteId: "q_lgh",
      address: "Storgatan 5, lgh 1203, 114 51 Stockholm",
      managerId: "u_johan",
      memberIds: ["u_erik", "u_sara"],
      startDate: dateOnly(-2),
      endDate: dateOnly(6),
      budget: 29800,
      laborBudgetHours: 42,
      materialBudget: 6400,
      status: "active",
      createdAt: dayISO(-15),
    },
  ];

  /* ------------------------------ Work orders ------------------------------ */
  const workOrders: WorkOrder[] = [
    {
      id: "wo_1",
      organizationId: ORG_ID,
      number: "AO-2026-031",
      customerId: "c_anders",
      projectId: "p_lgh",
      address: "Storgatan 5, lgh 1203, 114 51 Stockholm",
      title: "Spackling och grundning – vardagsrum",
      description: "Spackla väggar, slipa och grunda inför målning.",
      instructions: "Täck golv noggrant. Nyckel hämtas hos granne lgh 1201.",
      assigneeIds: ["u_erik", "u_sara"],
      supervisorId: "u_johan",
      date: dateOnly(0),
      startTime: "08:00",
      estimatedEndTime: "12:00",
      priority: "normal",
      status: "in_progress",
      checklist: [
        { id: "cl_1", label: "Täck golv och möbler", done: true },
        { id: "cl_2", label: "Spackla väggar", done: true },
        { id: "cl_3", label: "Slipa", done: false },
        { id: "cl_4", label: "Grunda", done: false },
      ],
      createdAt: dayISO(-3),
    },
    {
      id: "wo_2",
      organizationId: ORG_ID,
      number: "AO-2026-032",
      customerId: "c_anders",
      projectId: "p_lgh",
      address: "Storgatan 5, lgh 1203, 114 51 Stockholm",
      title: "Målning väggar och tak – vardagsrum",
      description: "Två strykningar väggar och tak enligt offert.",
      instructions: "Färgkod NCS S 0502-Y. Kontrollera med kund före start.",
      assigneeIds: ["u_erik"],
      supervisorId: "u_johan",
      date: dateOnly(0),
      startTime: "13:00",
      estimatedEndTime: "16:30",
      priority: "normal",
      status: "planned",
      checklist: [
        { id: "cl_5", label: "Första strykning", done: false },
        { id: "cl_6", label: "Andra strykning", done: false },
        { id: "cl_7", label: "Slutkontroll", done: false },
      ],
      createdAt: dayISO(-3),
    },
    {
      id: "wo_3",
      organizationId: ORG_ID,
      number: "AO-2026-033",
      customerId: "c_brf",
      address: "Solvägen 22, 129 32 Hägersten",
      title: "Besiktning trapphus inför offert",
      description: "Inmätning och fotodokumentation av två trapphus.",
      instructions: "Portkod 1984. Möt ordförande Margareta vid entré A.",
      assigneeIds: ["u_johan"],
      supervisorId: "u_johan",
      date: dateOnly(1),
      startTime: "09:00",
      estimatedEndTime: "10:30",
      priority: "normal",
      status: "planned",
      checklist: [],
      createdAt: dayISO(-2),
    },
    {
      id: "wo_4",
      organizationId: ORG_ID,
      number: "AO-2026-030",
      customerId: "c_anders",
      projectId: "p_lgh",
      address: "Storgatan 5, lgh 1203, 114 51 Stockholm",
      title: "Förarbete hall",
      description: "Förarbete och spackling i hall.",
      assigneeIds: ["u_sara"],
      supervisorId: "u_johan",
      date: dateOnly(-2),
      startTime: "08:00",
      estimatedEndTime: "11:00",
      priority: "normal",
      status: "review",
      checklist: [
        { id: "cl_8", label: "Spackling klar", done: true },
        { id: "cl_9", label: "Slipning klar", done: true },
      ],
      createdAt: dayISO(-4),
    },
    {
      id: "wo_5",
      organizationId: ORG_ID,
      number: "AO-2026-029",
      customerId: "c_fastpartner",
      address: "Ekvägen 8, 168 53 Bromma",
      title: "Akut bättringsmålning entré",
      description: "Klottersanering och bättringsmålning vid entré B.",
      instructions: "Fakturareferens: DRIFT-2287.",
      assigneeIds: ["u_erik"],
      supervisorId: "u_johan",
      date: dateOnly(-1),
      startTime: "07:30",
      estimatedEndTime: "09:30",
      priority: "high",
      status: "completed",
      checklist: [{ id: "cl_10", label: "Klottersanering", done: true }],
      createdAt: dayISO(-5),
    },
    {
      id: "wo_6",
      organizationId: ORG_ID,
      number: "AO-2026-034",
      customerId: "c_fastpartner",
      address: "Ekvägen 8, 168 53 Bromma",
      title: "Målning gemensamhetslokal",
      description: "Målning av gemensamhetslokal, väntar på färgleverans.",
      assigneeIds: ["u_sara"],
      supervisorId: "u_johan",
      date: dateOnly(2),
      startTime: "08:00",
      estimatedEndTime: "16:00",
      priority: "normal",
      status: "waiting_material",
      checklist: [],
      createdAt: dayISO(-1),
    },
  ];

  /* ------------------------------ Time entries ----------------------------- */
  const timeEntries: TimeEntry[] = [
    {
      id: "te_1",
      organizationId: ORG_ID,
      workOrderId: "wo_4",
      userId: "u_sara",
      date: dateOnly(-2),
      minutes: 180,
      workType: "Förarbete",
      comment: "Spackling och slipning hall.",
      status: "approved",
    },
    {
      id: "te_2",
      organizationId: ORG_ID,
      workOrderId: "wo_5",
      userId: "u_erik",
      date: dateOnly(-1),
      minutes: 120,
      workType: "Bättringsmålning",
      status: "submitted",
    },
    {
      id: "te_3",
      organizationId: ORG_ID,
      workOrderId: "wo_1",
      userId: "u_erik",
      date: dateOnly(0),
      minutes: 95,
      workType: "Spackling",
      status: "running",
      startedAt: atTime(today, Math.max(8, today.getHours() - 1), 30),
    },
  ];

  /* -------------------------------- Materials ------------------------------ */
  const materials: MaterialEntry[] = [
    {
      id: "m_1",
      organizationId: ORG_ID,
      workOrderId: "wo_1",
      projectId: "p_lgh",
      name: "Väggfärg Beckers Scotte 7, vit",
      articleNumber: "BCK-7-10L",
      quantity: 3,
      unit: "st",
      purchasePrice: 540,
      customerPrice: 720,
      supplier: "Colorama",
      createdBy: "u_erik",
      createdAt: dayISO(0),
    },
    {
      id: "m_2",
      organizationId: ORG_ID,
      workOrderId: "wo_1",
      projectId: "p_lgh",
      name: "Spackel Gyproc Light",
      articleNumber: "GYP-LT-5L",
      quantity: 2,
      unit: "st",
      purchasePrice: 185,
      customerPrice: 260,
      supplier: "Beijer",
      createdBy: "u_erik",
      createdAt: dayISO(0),
    },
    {
      id: "m_3",
      organizationId: ORG_ID,
      workOrderId: "wo_5",
      name: "Klotterborttagning + bättringsfärg",
      quantity: 1,
      unit: "st",
      purchasePrice: 420,
      customerPrice: 650,
      supplier: "Colorama",
      createdBy: "u_erik",
      createdAt: dayISO(-1),
    },
  ];

  const attachments: Attachment[] = [
    {
      id: "att_1",
      organizationId: ORG_ID,
      workOrderId: "wo_4",
      projectId: "p_lgh",
      category: "before",
      url: "",
      fileName: "hall-fore.jpg",
      comment: "Hall före spackling.",
      uploadedBy: "u_sara",
      createdAt: dayISO(-2),
    },
    {
      id: "att_2",
      organizationId: ORG_ID,
      workOrderId: "wo_5",
      category: "after",
      url: "",
      fileName: "entre-efter.jpg",
      comment: "Entré efter sanering.",
      uploadedBy: "u_erik",
      createdAt: dayISO(-1),
    },
  ];

  const changeOrders: ChangeOrder[] = [
    {
      id: "co_1",
      organizationId: ORG_ID,
      projectId: "p_lgh",
      workOrderId: "wo_2",
      description: "Extra strykning på tak pga fläckar som slog igenom.",
      reason: "Underlaget krävde en tredje strykning för täckning.",
      estimatedHours: 4,
      price: 2725,
      status: "sent",
      publicToken: "tok_co_4d2a",
      createdAt: dayISO(0),
    },
  ];

  const invoiceDrafts: InvoiceDraft[] = [
    {
      id: "inv_1",
      organizationId: ORG_ID,
      number: "FAKT-2026-008",
      customerId: "c_fastpartner",
      workOrderId: "wo_5",
      reference: "DRIFT-2287",
      items: [
        {
          id: "ii_1",
          description: "Klottersanering och bättringsmålning entré",
          quantity: 2,
          unit: "tim",
          unitPrice: 595,
          vatRate: 25,
        },
        {
          id: "ii_2",
          description: "Material – klotterborttagning + färg",
          quantity: 1,
          unit: "st",
          unitPrice: 650,
          vatRate: 25,
        },
      ],
      status: "draft",
      createdAt: dayISO(0),
    },
  ];

  const notifications: AppNotification[] = [
    {
      id: "n_1",
      organizationId: ORG_ID,
      kind: "quote_approved",
      title: "Offert godkänd",
      body: "Anders Andersson godkände OFF-2026-014 – Målning av lägenhet.",
      href: "/quotes/q_lgh",
      read: false,
      createdAt: dayISO(-15),
    },
    {
      id: "n_2",
      organizationId: ORG_ID,
      kind: "quote_opened",
      title: "Offert öppnad",
      body: "Fastighetspartner öppnade OFF-2026-021 – Fasadmålning.",
      href: "/quotes/q_fasad",
      read: false,
      createdAt: dayISO(-2),
    },
    {
      id: "n_3",
      organizationId: ORG_ID,
      userId: "u_johan",
      kind: "change_order_pending",
      title: "Tilläggsarbete väntar",
      body: "Tilläggsarbete på AO-2026-032 väntar på kundgodkännande.",
      href: "/projects/p_lgh",
      read: false,
      createdAt: dayISO(0),
    },
    {
      id: "n_4",
      organizationId: ORG_ID,
      userId: "u_johan",
      kind: "work_order_review",
      title: "Klar för kontroll",
      body: "AO-2026-030 (förarbete hall) är markerad klar för kontroll.",
      href: "/work-orders/wo_4",
      read: true,
      createdAt: dayISO(-2),
    },
  ];

  const activity: ActivityLog[] = [
    {
      id: "a_1",
      organizationId: ORG_ID,
      actorId: "u_anna",
      actorName: "Anna Lind",
      action: "skapade offert",
      entityType: "quote",
      entityId: "q_vatten",
      href: "/quotes/q_vatten",
      createdAt: dayISO(-1),
    },
    {
      id: "a_2",
      organizationId: ORG_ID,
      actorName: "Anders Andersson",
      action: "godkände offert OFF-2026-014",
      entityType: "quote",
      entityId: "q_lgh",
      href: "/quotes/q_lgh",
      createdAt: dayISO(-15),
    },
    {
      id: "a_3",
      organizationId: ORG_ID,
      actorId: "u_erik",
      actorName: "Erik Nilsson",
      action: "startade tidregistrering på AO-2026-031",
      entityType: "work_order",
      entityId: "wo_1",
      href: "/work-orders/wo_1",
      createdAt: dayISO(0),
    },
    {
      id: "a_4",
      organizationId: ORG_ID,
      actorId: "u_sara",
      actorName: "Sara Ali",
      action: "markerade AO-2026-030 klar för kontroll",
      entityType: "work_order",
      entityId: "wo_4",
      href: "/work-orders/wo_4",
      createdAt: dayISO(-2),
    },
  ];

  return {
    organization,
    users,
    customers,
    inquiries,
    quotes,
    projects,
    workOrders,
    timeEntries,
    materials,
    attachments,
    changeOrders,
    invoiceDrafts,
    notifications,
    activity,
  };
}
